### ISSUE TITLE
Using the recent/episodes endpoint to walk back through episode history has an inconsistency

### ISSUE THREAD

**Issue by SarvagyaVaish** [Podcastindex-org/aggregator#6]
I ran the recent/episodes endpoint and received the following (it's just a coincidence that i can the api at exactly the top of the hour, dont let that distract 😉):

```
id: 1311311529 date: December 20, 2020 12:14am
id: 1311313025 date: December 20, 2020 12:14am
id: 1311314553 date: December 20, 2020 12:13am
id: 1311314978 date: December 20, 2020 12:05am
id: 1311302852 date: December 20, 2020 12:05am
id: 1311293451 date: December 20, 2020 12:02am
id: 1311291755 date: December 20, 2020 12:02am
id: 1311292652 date: December 20, 2020 12:02am
id: 1311286784 date: December 20, 2020 12:01am
id: 1311302923 date: December 20, 2020 12:00am
```

Note: The episodes are ordered by the datePublished field, not the episode id field. Id in row 2 is higher than that in row 1. 

This is fine in general, and the [docs](https://podcastindex-org.github.io/docs-api/) state that the episodes are returned in reverse chronological order. However, since the episodes are not ordered by ID, we can't use the ID field to "walk back through the episode history sequentially". 

Is my understanding correct? If so perhaps we can clarify this nuance in the api-docs :)

**Comment by SarvagyaVaish** [comment]
@daveajones this is a bit nit picky, and apologies in advance for that :)
I found this inconsistency while writing tests for the [python api wrapper](https://github.com/SarvagyaVaish/python-podcastindex).

**Comment by daveajones** [comment]
Interesting. Let me go back and look at that code so I can see what’s happening.

**Comment by daveajones** [comment]
This should be fixed now.  Just a wrong ORDER BY statement.

**Comment by SarvagyaVaish** [comment]
> This should be fixed now. Just a wrong ORDER BY statement.

Nice! What was the issue?

**Comment by daveajones** [comment]
It was just a wrong field in the ORDER BY.  I changed it to order by ID desc instead of pubtime.  Pretty much just as you reported.  They are so close to each other that I never noticed the issue.

**Comment by SarvagyaVaish** [comment]
> It was just a wrong field in the ORDER BY. I changed it to order by ID desc instead of pubtime. Pretty much just as you reported. They are so close to each other that I never noticed the issue.

Nice! Thanks for fixing :)
